# This file contains some arcane technical incantations that are needed to
# enable code coverage tracking via continuous integration.
# It is not an integral part of the project and I'd rather remove it if I could help it.

language: objective-c
osx_image: xcode7.2
before_script:
 - brew update
script: xcrun xcodebuild -project TreeCollections.xcodeproj -scheme TreeCollections-Mac test
after_success: bash <(curl -s https://codecov.io/bash)
